# https://resilience4j.readme.io/docs/getting-started-3
# https://resilience4j.readme.io/docs/circuitbreaker
resilience4j.circuitbreaker:
    configs:
      default:
        ringBufferSizeInClosedState: 5 # 熔断器关闭时的缓冲区大小 - 达到缓冲区开始计算failure rate
        ringBufferSizeInHalfOpenState: 2 # 熔断器半开时的缓冲区大小 - 达到缓冲区开始计算failure rate
        waitDurationInOpenState: 10000 # 熔断器从打开状态转变为半开状态等待的时间 - 单位: 秒
        failureRateThreshold: 60 # 熔断器打开的失败阈值 - 百分比
        eventConsumerBufferSize: 10 # 事件缓冲区大小
        registerHealthIndicator: true # 健康监测
        automaticTransitionFromOpenToHalfOpenEnabled: true # 如果置为true, 当等待时间结束会自动由打开变为半开, 若置为false, 则需要一个请求进入来触发熔断器状态转换
        recordExceptions: # 记录的异常
          - resilience4j.by.taoyangui.exception.BusinessBException
          - resilience4j.by.taoyangui.exception.BusinessAException
        ignoreExceptions: # 忽略的异常 - 具备较高优先级 - Ignoring an exception has priority over recording an exception
          - resilience4j.by.taoyangui.exception.BusinessAException # 看出白名单所谓的忽略, 是指不计入缓冲区中(即不算成功也不算失败)
    instances:
      backendA:
        baseConfig: default # inherit from above "default"
        waitDurationInOpenState: 3000
        failureRateThreshold: 20
      backendB:
        baseConfig: default
