#logging:
#  level:
#    ROOT: DEBUG
# https://resilience4j.readme.io/docs/getting-started-3
# https://resilience4j.readme.io/docs/circuitbreaker
resilience4j.circuitbreaker:
  configs:
    default:
      # CLOSED
      ringBufferSizeInClosedState: 5 # 熔断器关闭时的缓冲区大小 - 达到缓冲区值开始计算failure rate
      failureRateThreshold: 60 # 熔断器打开的失败阈值 - 百分比
      # 如果由这部分设置, 则所有记录的异常都要在这里设置, 否则会被忽略
      # recordExceptions: # 记录的异常
      #  - resilience4j.by.taoyangui.exception.BusinessBException
      #  - resilience4j.by.taoyangui.exception.BusinessAException
      ignoreExceptions: # 忽略的异常 - 具备较高优先级 - Ignoring an exception has priority over recording an exception
        - resilience4j.by.taoyangui.exception.BusinessAException # 看出白名单所谓的忽略, 是指不计入缓冲区中(即不算成功也不算失败)
      # HALF OPEN
      waitDurationInOpenState: 10000 # 熔断器从打开状态转变为半开状态等待的时间 - 单位: 秒
      automaticTransitionFromOpenToHalfOpenEnabled: true # 如果置为true, 当等待时间结束会自动由打开变为半开, 若置为false, 则需要一个请求进入来触发熔断器状态转换
      ringBufferSizeInHalfOpenState: 3 # 熔断器半开时的缓冲区大小 - 达到缓冲区值开始计算failure rate;
      ## ringBufferSizeInHalfOpenState超过ringBufferSizeInClosedState, 则取ringBufferSizeInClosedState的值
      ## use the same rate of "failureRateThreshold"
      # monitoring
      registerHealthIndicator: true # 健康监测
      eventConsumerBufferSize: 10 # SpringBoot2 actuator缓冲区记录事件数 - https://resilience4j.readme.io/v0.17.0/docs/getting-started-3#events-endpoint
  instances:
    backendA:
      baseConfig: default # inherit from above "default"
      waitDurationInOpenState: 3000
      failureRateThreshold: 20
    backendB:
      baseConfig: default

resilience4j.timelimiter:
  instances:
    backendA:
      timeoutDuration: 2s
      cancelRunningFuture: true
    backendB:
      timeoutDuration: 1s
      cancelRunningFuture: false

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 4 # 重试多3次
      waitDuration: 10s
#      enableExponentialBackoff: true # 是否允许使用指数退避算法进行重试间隔时间的计算
#      expontialBackoffMultiplier: 2 # 指数退避算法的乘数
#      enableRandomizedWait: false # 是否允许使用随机的重试间隔
#      randomizedWaitFactor: 0.5 # 随机因子
#      resultPredicate: resilience4j.by.taoyangui.service.RetryResultPredicate
#      retryExceptionPredicate: resilience4j.by.taoyangui.service.RetryPredicate
      retryExceptions:
        - resilience4j.by.taoyangui.exception.BusinessBException
      ignoreExceptions: # 不会retry
        - resilience4j.by.taoyangui.exception.BusinessAException
  instances:
    backendA:
      baseConfig: default
      waitDuration: 3s
    backendB:
      baseConfig: default
      maxRetryAttempts: 2
